# ============================================================
# SerikaOS — Calamares Settings
# ============================================================

modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  - id:       serikaos
    module:   netinstall
    config:   netinstall.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - netinstall@serikaos
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - networkcfg
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - luksbootkeyfile
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - initcpio
      - grubcfg
      - bootloader
      - packages
      - shellprocess
      - umount
  - show:
      - finished

branding: serikaos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
