# SerikaOS — Display Manager Module
---
displaymanagers:
    - sddm
    - gdm
    - lightdm
    - ly

defaultDesktopEnvironment:
    executable: "startplasma-wayland"
    desktopFile: "plasma"

basicSetup: false
sysconfigSetup: false
