# SerikaOS — Partition Module
---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true

initialPartitioningChoice: erase
defaultPartitionTableType: gpt

initialSwapChoice: small

defaultFileSystemType: "btrfs"
availableFileSystemTypes:
    - "btrfs"
    - "ext4"
    - "xfs"
    - "f2fs"

requiredPartitionTableType:
    - gpt

luksGeneration: luks2
allowZfsEncryption: false
